# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(710, 710)
        MainWindow.setMinimumSize(QtCore.QSize(710, 710))
        MainWindow.setMaximumSize(QtCore.QSize(710, 710))
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.run_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.run_pushButton.setGeometry(QtCore.QRect(590, 30, 99, 31))
        self.run_pushButton.setObjectName("run_pushButton")
        self.tests_comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.tests_comboBox.setGeometry(QtCore.QRect(20, 30, 551, 31))
        self.tests_comboBox.setObjectName("tests_comboBox")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 10, 121, 17))
        self.label.setObjectName("label")
        self.dial = QtWidgets.QDial(self.centralwidget)
        self.dial.setGeometry(QtCore.QRect(520, 110, 131, 151))
        self.dial.setMaximum(4)
        self.dial.setProperty("value", 1)
        self.dial.setNotchTarget(1.0)
        self.dial.setNotchesVisible(True)
        self.dial.setObjectName("dial")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(20, 80, 451, 591))
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.South)
        self.tabWidget.setObjectName("tabWidget")
        self.testSequenceTab = QtWidgets.QWidget()
        self.testSequenceTab.setObjectName("testSequenceTab")
        self.sequence_tableWidget = QtWidgets.QTableWidget(self.testSequenceTab)
        self.sequence_tableWidget.setGeometry(QtCore.QRect(10, 34, 421, 521))
        self.sequence_tableWidget.setObjectName("sequence_tableWidget")
        self.sequence_tableWidget.setColumnCount(2)
        self.sequence_tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.sequence_tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.sequence_tableWidget.setHorizontalHeaderItem(1, item)
        self.label_6 = QtWidgets.QLabel(self.testSequenceTab)
        self.label_6.setGeometry(QtCore.QRect(10, 10, 111, 16))
        self.label_6.setObjectName("label_6")
        self.tabWidget.addTab(self.testSequenceTab, "")
        self.diagnosticsTab = QtWidgets.QWidget()
        self.diagnosticsTab.setObjectName("diagnosticsTab")
        self.diagnostics_textEdit = QtWidgets.QTextEdit(self.diagnosticsTab)
        self.diagnostics_textEdit.setEnabled(True)
        self.diagnostics_textEdit.setGeometry(QtCore.QRect(10, 34, 421, 521))
        self.diagnostics_textEdit.setObjectName("diagnostics_textEdit")
        self.label_5 = QtWidgets.QLabel(self.diagnosticsTab)
        self.label_5.setGeometry(QtCore.QRect(10, 10, 101, 17))
        self.label_5.setObjectName("label_5")
        self.tabWidget.addTab(self.diagnosticsTab, "")
        self.temperature_label = QtWidgets.QLabel(self.centralwidget)
        self.temperature_label.setGeometry(QtCore.QRect(500, 320, 91, 41))
        self.temperature_label.setStyleSheet("font-size: 20px;")
        self.temperature_label.setObjectName("temperature_label")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(500, 300, 121, 17))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.status_groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.status_groupBox.setGeometry(QtCore.QRect(490, 540, 201, 111))
        self.status_groupBox.setObjectName("status_groupBox")
        self.stm24Com_checkBox = QtWidgets.QCheckBox(self.status_groupBox)
        self.stm24Com_checkBox.setGeometry(QtCore.QRect(30, 33, 131, 17))
        self.stm24Com_checkBox.setCheckable(True)
        self.stm24Com_checkBox.setObjectName("stm24Com_checkBox")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(490, 160, 46, 13))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(570, 100, 46, 13))
        self.label_3.setObjectName("label_3")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(657, 160, 46, 13))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(620, 250, 46, 13))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(530, 250, 46, 13))
        self.label_11.setObjectName("label_11")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(489, 390, 201, 111))
        self.groupBox.setObjectName("groupBox")
        self.canCom_checkBox = QtWidgets.QCheckBox(self.groupBox)
        self.canCom_checkBox.setGeometry(QtCore.QRect(30, 34, 131, 17))
        self.canCom_checkBox.setCheckable(True)
        self.canCom_checkBox.setObjectName("canCom_checkBox")
        self.brakeEngaged_checkBox = QtWidgets.QCheckBox(self.groupBox)
        self.brakeEngaged_checkBox.setGeometry(QtCore.QRect(30, 64, 111, 17))
        self.brakeEngaged_checkBox.setObjectName("brakeEngaged_checkBox")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 710, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "GHSP - Noise Simulation Tool"))
        self.run_pushButton.setText(_translate("MainWindow", "Run"))
        self.label.setText(_translate("MainWindow", "Select Test Sequence"))
        item = self.sequence_tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Name"))
        item = self.sequence_tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Status"))
        self.label_6.setText(_translate("MainWindow", "Sequence"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.testSequenceTab), _translate("MainWindow", "Test Sequence"))
        self.label_5.setText(_translate("MainWindow", "Diagnostics"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.diagnosticsTab), _translate("MainWindow", "Diagnostics"))
        self.temperature_label.setText(_translate("MainWindow", "--"))
        self.label_8.setText(_translate("MainWindow", "Temperature (°F)"))
        self.status_groupBox.setTitle(_translate("MainWindow", "Status"))
        self.stm24Com_checkBox.setText(_translate("MainWindow", "STM24 Communication"))
        self.label_2.setText(_translate("MainWindow", "Park"))
        self.label_3.setText(_translate("MainWindow", "Reverse"))
        self.label_9.setText(_translate("MainWindow", "Neutral"))
        self.label_10.setText(_translate("MainWindow", "Drive"))
        self.label_11.setText(_translate("MainWindow", "Sport"))
        self.groupBox.setTitle(_translate("MainWindow", "CAN"))
        self.canCom_checkBox.setText(_translate("MainWindow", "CAN Communication"))
        self.brakeEngaged_checkBox.setText(_translate("MainWindow", "Brake Engaged"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
